name: ventura_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter 
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  http: ^1.2.1
  provider: ^6.1.2
  map_launcher: ^3.2.0
  flutter_dotenv: ^5.1.0
  simple_progress_indicators: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "lib/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets: 
    - lib/icons/
    - .env
    - lib/data/initial-locations.json