name: ventura_front
description: "Campus Interactive Map"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter 
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  http: ^1.2.1
  provider: ^6.1.2
  map_launcher: ^3.2.0
  flutter_dotenv: ^5.1.0
  simple_progress_indicators: ^0.2.0
  url_launcher: ^6.0.0
  proximity_sensor: ^1.3.1
  cached_network_image: ^3.0.0
  flutter_cache_manager: ^3.0.0
  firebase_core: ^2.31.0
  image_picker: ^1.1.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.3
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "lib/icons/icono.png"
  adaptative_icon_background: "lib/icons/icono.png"

flutter:
  uses-material-design: true
  assets: 
    - lib/icons/
    - .env
    - lib/data/initial-locations.json