name: ventura_front
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  http: ^1.2.1
  provider: ^6.1.2
  map_launcher: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/icons/
